Repository ringwormGO-organization/Termi, pull requests merged in 2023-12, with the labels that each got.

#12 add OpenBSD and NetBSD macros
  src/Termi-Commands/Commands.cpp
  src/Termi-Commands/Export.h
  src/Termi-GUI/imgui_code.hpp
  src/Termi-GUI/imgui_main.cpp
  src/Termi-GUI/main.cpp
  src/Termi-Main/main.cpp
Labels: enhancement, BSD

#15 Update README and remove `dl` when linking `Termi-GUI`
  README.md
  src/Termi-GUI/CMakeLists.txt
Labels: documentation, BSD

#19 Update translation.hpp
  src/Termi-GUI/translation.hpp
Labels: good first issue, translation

#20 Update base64.hpp
  src/Termi-Commands/Commands/base64.hpp
Labels: C++
